[package]
name = "maxtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
clap = { version = "4.3", features = ["derive"] }
pyo3="0.19"
